### ISSUE TITLE
panic: StructureError::NonSortedIndices

### ISSUE THREAD

**Issue by NeverGivinUp** [ztlpn/minilp#5]
I'm just starting to use minilp and it panics with an unwrapped `NonSortedIndices` error from the `sprs` crate when calling 
```
problem.add_constraint(
                    &[
                        (node_var, 1.0),
                        (other_node_var, -1.0),
                        (additional_var, -1.0),
                    ],
                    ComparisonOp::Le,
                    0.0,
                );
```
The panic originates from minilp's lib.rs  line 279
```
  CsVec::new(self.obj_coeffs.len(), expr.vars, expr.coeffs),
```

What am I doing wrong?

**Comment by ztlpn** [comment]
Hi, can you provide all code that creates the problem? Preferably as a self-contained example that reproduces the error.

This error can arise if you accidentally mention the same var twice in a single constraint.

**Comment by NeverGivinUp** [comment]
Thank you @ztlpn. That's exactly what happened: I included the same variable twice, as I could see, when logging the variables before defining the constraint. It's very good, that `minilp` catches such mistakes. A more clearly named error would be even better :) Thank you again!
